# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 22:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdressePostale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localite', models.CharField(max_length=120)),
                ('rue', models.CharField(max_length=120)),
                ('code_postal', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Partenaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_de_relation', models.CharField(choices=[('M', 'Mariage'), ('V', 'Veuvage'), ('D', 'Divorcé'), ('C', 'Concubinage'), ('S', 'Séparé')], max_length=1)),
                ('date_du_statut', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_de_famille', models.CharField(max_length=120)),
                ('prenom', models.CharField(max_length=120)),
                ('date_de_naissance', models.DateField(null=True)),
                ('date_de_deces', models.DateField(null=True)),
                ('est_paroissien', models.BooleanField(default=False)),
                ('adressePostale', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.AdressePostale')),
                ('enfants', models.ManyToManyField(to='crm.Personne')),
                ('mere', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='crm.Personne')),
                ('partenaires', models.ManyToManyField(to='crm.Partenaire')),
                ('pere', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='crm.Personne')),
            ],
        ),
        migrations.CreateModel(
            name='Telephone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_de_telephone', models.CharField(max_length=100)),
                ('type_de_telephone', models.CharField(choices=[('M', 'Mobile'), ('F', 'Fixe')], max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='personne',
            name='telephones',
            field=models.ManyToManyField(to='crm.Telephone'),
        ),
        migrations.AddField(
            model_name='partenaire',
            name='partenaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Personne'),
        ),
    ]
